route:
  group_by: ['alertname', 'topic', 'stage']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 1h
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - api_url_file: /etc/alertmanager/slack_webhook_url
        channel: '#all-self-made'
        username: 'Boltstream Alertmanager'
        send_resolved: true
        icon_emoji: ':rotating_light:'
        title: '{{ .CommonLabels.alertname }} ({{ .Status }})'
        text: >-
          *Summary*: {{ .CommonAnnotations.summary }}
          *Description*: {{ .CommonAnnotations.description }}
          *Labels*: {{ .CommonLabels }}
          *StartsAt*: {{ (index .Alerts 0).StartsAt }}
          *EndsAt*: {{ (index .Alerts 0).EndsAt }}